# Generated by Django 3.1.7 on 2021-04-05 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platecheck_plate', models.CharField(help_text='AAA123 / AAA1234', max_length=7, validators=[django.core.validators.RegexValidator('^[a-z&&[^df]A-Z&&[^df]]{1}[a-zA-Z]{2}[0-9]{3,4}$', 'Please check plate format AAA123 or AAA1234.')], verbose_name='Plate')),
                ('platecheck_date', models.DateField()),
                ('platecheck_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Plate Check',
                'verbose_name_plural': 'Plates Checked',
            },
        ),
    ]
