version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_pgadmin_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: picoplaca_local_django
    container_name: picoplaca_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: picoplaca_production_postgres
    container_name: picoplaca_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: picoplaca_local_docs
    container_name: picoplaca_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./picoplaca:/app/picoplaca:z
    ports:
      - "7000:7000"
    command: /start-docs

#  Uncomment to use pgadmin
  pgadmin:
    build:
      context: .
      dockerfile: ./compose/local/pgadmin/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.pgadmin
    logging:
      driver: none
    ports:
      - "5050:5050"
    volumes:
      - local_pgadmin_data:/var/lib/pgadmin:z
